name: Publish CI

on:
  push:
    branches:
      - 'beta'

env:
  NPM_AUTH: ${{secrets.NPM_AUTH}}    

jobs:  
  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn
    - run: yarn lint:check
    - run: yarn pretty:check
    - run: CI=false yarn build
    - run: npm publish
